/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'sykim' at '15. 11. 20 오전 9:53' with Gradle 2.9
 *
 * @author sykim, @date 15. 11. 20 오전 9:53
 */
public class Dollar {

	int amount;

	Dollar(int amount) {
		this.amount = amount;	
	}
	
	Dollar times(int multiplier) {
		return new Dollar(amount * multiplier);
	}

	public boolean equals(Object object) {
		Dollar dollar = (Dollar) object;
		return amount == dollar.amount;
	}

}
