import org.junit.Test;
import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'sykim' at '15. 11. 20 오전 9:53' with Gradle 2.9
 *
 * @author sykim, @date 15. 11. 20 오전 9:53
 */
public class MoneyTest {
    @Test
	public void testMultiplication() {
		Dollar five = new Dollar(5);
    	five.times(2);
		assertEquals(10, five.amount);
		product = five.times(3);
        assertEquals(15, product.amount);
	}
}
